### ISSUE TITLE
Why are GROOVY, KOTLIN, and SQL included in almost every flavor?

### ISSUE THREAD

**Issue by IlanCosman** [megalinter/megalinter#1090]
I was just curious about this. They aren't very popular languages as far as I can tell according to [github data](https://madnight.github.io/githut/#/pull_requests/2021/3) and my own knowledge. Most project probably have a few bash scripts lying around, but not groovy, kotlin, or sql stuff.

**Comment by nvuillam** [comment]
Groovy & Kotlin are used in CI tools :
- Groovy -> There can be Jenkinsfile in any repo
- Kotlin -> TeamCity pipelines language

SQL, not popular ? :D

But I agree with you that flavors could again be pimped... the problem is that I have no idea about the combinations used by projects linted by MegaLinter... the only way to do that would be to set some telemetry, but I'm afraid it would scare some users that would be afraid that I gather their code :D ( MegaLinter is also used on companies private Github / Gitlab / Azure / Bitbucket instances )

**Comment by IlanCosman** [comment]
> Groovy -> There can be Jenkinsfile in any repo
> Kotlin -> TeamCity pipelines language

Ah, ok, I didn't realize those are used for CI, fair enough. Thanks for enlightening me 😄

**Comment by nvuillam** [comment]
@IlanCosman I didn't know about Kotlin and TeamCity before a contributor asked for it for this reason ;)
