### ISSUE TITLE
SQL FLUFF not being found

### ISSUE THREAD

**Issue by gregmaghakian** [megalinter/megalinter#1407]
I have my .mega-linter.yml configured for certain linters for the slimmed down python image of mega linter. currently it is defined as 
```
ENABLE_LINTERS:
  - SQL_SQLFLUFF
  - PYTHON_BLACK
  - R_LINTR 
```

However when github actions runs, it doesn't seem to pick up my changed sql file. For instance, the other sql linters do, but not this one. Has anyone had success implementing sqlfluff?

**Comment by nvuillam** [comment]
Since [latest sqlfluff version 0.12.0](https://github.com/sqlfluff/sqlfluff/releases/tag/0.12.0), it is mandatory to specify a SQL dialect
You can do that by copying [this **.sqlfluff** file](https://github.com/megalinter/megalinter/blob/main/TEMPLATES/.sqlfluff) at the root of your repository,  uncomment **dialect** property and specify a value

@tunetheweb maybe you have additional info ? This breaking change may impact lots of MegaLinter users ^^

**Comment by tunetheweb** [comment]
Hey all, apologies for any disruption here. We did try to make this breaking change clear in the change log, on [our Twitter account](https://twitter.com/SQLFluff/status/1511640295024308224?s=20&t=xMy7uDM1xq67qZyquCwbUA) and in our Slack channel. But appreciate not everyone (especially those using it via projects like Megalinter) got then message.

The default dialect was our `ansi` dialect, which is more a generic base dialect rather than one that should really be used. There is no ANSI database, but various variants of this (Postgres, Oracle, T-SQL...etc.) each with slight differences from the dialect.

Therefore it's very unlikely users really want to use the `ansi` dialect, and there's likely a much better dialect that should be used instead. So it wasn't a great default in all honesty. We were getting a number of support queries from, for example, Postgres users stating their Postgres SQL wasn't working in SQLFluff, when it was if they just knew to set the dialect. We therefore took the decision to remove the default dialect and insist that users set this, either in the command line (using the `--dialect ansi` option for example), or via a sqlfluff config file. We also hope getting users use to configuring SQLFluff will allow them to look at setting up the other config to their needs, rather than just accepting the defaults.

Hopefully that explains the rational.

However, I am curious as to why this doesn't fail as we exit with a non-zero exit code. So it shouldn't just "not lint", but should instead alert you to the problem, with an error message explaining the need to set the dialect.

**Comment by nvuillam** [comment]
@tunetheweb thanks for the explanations :)

I detected the crash during CI test classes... then I decided to **activate SQLFLUFF only if a .sqlfluff file is defined within the repository**  -> https://megalinter.github.io/latest/descriptors/sql_sqlfluff/#how-are-identified-applicable-files

**Comment by tunetheweb** [comment]
Oh yeah should have thought about your CI test. Did you update that to have the dialect command line?

And cause you also support command line arguments for regular use too, you don’t technically need a config file as they could use that. But most likely it would be configured in a config file.

Still, I’m not convinced silently disabling it is the right way to go to be honest…

**Comment by nvuillam** [comment]
I need MegaLinter to be "plug & play", I can not have a linter failing by default just because its required configuration has not been defined :/

I understand why you made the change that you made... but users are usually asking something immediately ready ... and I think that is the same for sqlfluff standalone users: Instead of returning a 1 code to request  configuration file or argument, would you consider doing something like displaying a warning when default "ansi" dialect is detected ? **You are using default dialect ansi: for more accurate results, please select your SQL dialect by defining property dialect within .sqlfluff file, or add argument --dialect in the command line arguments. Available values are: .....**

**Comment by tunetheweb** [comment]
It always printed that warning in the past. The fact you didn’t know that (because you never saw it) shows why it wasn’t enough, as many were running it in CI/CD or similar and ignored warnings.

IMHO users of megalinter are used to looking at the logs for linting failures to get the details of why it failed.

**Comment by tunetheweb** [comment]
> I'm curious to see how SuperLinter neighbours will manage the issue ...

Yes that’ll be interesting. Going to raise an issue on that today. I see the PR of 0.12.0 is failing as their test is failing due to lack of a dialect so will let them know, and warn them if this breaking change.

Will let you know of how they handle it and if I hear of any issues/complaints.

**Comment by nvuillam** [comment]
My point is that SQL is pretty much the same in 80% of the cases, so forcing to define a configuration for the 20% remaining cases is in my opinion less "inclusive" for the majority of use cases, and that the 20% of cases should not negatively impact the 80% of the "easy" cases

But again, it's opiniotated, your arguments are good too !

**Comment by tunetheweb** [comment]
That 20% becomes pretty relevant, pretty quickly. Only the most basic SQL is the same (for which the need for a linter is questionable).

Although SQL looks the same, the subtle differences really do matter. ANSI SQL is not an implemented language - you cannot use an ANSI SQL server anywhere because it doesn't exist. EVERY SQL server is using significant variants on it. Be that additional (reserved) keywords, additional syntax, or unimplemented ANSI grammar. So ANSI is a poor choice for a default. But the SQL world is so fragmented that any other choice has it's own issues too. We really do need the user to tell us what SQL dialect they are using for us to properly be able to lint their SQL.

As I say, we got enough issues raised on GitHub, and questions asked to us on Slack and through other means to feel this was a worthwhile change for us.

I think the question for Megalinter is, are you more likely to get issues raised, and confusion, by silently not linting SQL files, or by just surfacing the linting error message we provide (i.e. that a dialect is missing)?

Maybe you could add a section here, to say either the `--dialect` needs to be provided in `SQL_SQLFLUFF_ARGUMENTS` or a ``sqlfluff config needs to be provided with that set as part of enabling?:

<img width="605" alt="image" src="https://user-images.githubusercontent.com/10931297/162906095-0c73adb0-4340-4a8d-84d2-523eed57db1d.png">

**Comment by nvuillam** [comment]
I'll update the documentation to give such info at the top , that's planned yes :)

**Comment by tunetheweb** [comment]
FYI: https://github.com/github/super-linter/issues/2785

**Comment by gregmaghakian** [comment]
@nvuillam , @tunetheweb , many thanks to both of you! Works great for me with the added config file, specifying the dialect. Am I good to close this out?

**Comment by nvuillam** [comment]
@gregmaghakian let's close once I updated the documentation to make such info more visible :)

**Comment by tunetheweb** [comment]
I still think you should reconsider failing silently. I think it’ll just lead to more, similar, issues being raised for you in future.

Sure, failing, because you never set up your config is annoying I agree, but obvious and easily fixable.

Not failing and seeming to work, but not actually doing the linting, is worse and confusing IMHO.

**Comment by odette-ppb** [comment]
Hello!

I've had the same issue with SQLfluff not being activated for the python flavour, although I do have a .sqlfluff configuration file located in .gihtub/linters, as I set the LINTER_RULES_PATH. This has worked as expected until now, using the postgres dialect.

Is there a possibility to look into LINTER_RULES_PATH for the .sqlfluff config file instead of root, at the activation step?

**Comment by nvuillam** [comment]
Please could you share you `.mega-linter.yml` config file , and run again the command with LOG_LEVEL=DEBUG and share the log ?

( you can hide/remove the parts that you don't want to be public)

**Comment by odette-ppb** [comment]
Hey, I've attached the relevant logs + mega-linter config

[202204131035__megalinter.txt](https://github.com/megalinter/megalinter/files/8480754/202204131035__megalinter.txt)
[linter_config.yml.txt](https://github.com/megalinter/megalinter/files/8480756/linter_config.yml.txt)

**Comment by tunetheweb** [comment]
> [Activation] SQL_SQLFLUFF has been set inactive, as none of these files has been found: ['.sqlfluff']

@odette-ppb can you confirm that `.gihtub/linters/.sqlfluff` definitely exists? And there's not a typo or anything (I often type it as `.sqlfuff` for example cause I'm an idiot 😁)

**Comment by odette-ppb** [comment]
yep, it exists under .github\linters\.sqlfluff
what's strange is that it has worked in the past, I've only noticed today it doesn't work anymore, after about two weeks of inactivity on the repository (nothing changed in the config or repo as far as I know)
the repository is not very active at the moment, the last change + successful run was around 15 days ago.

**Comment by tunetheweb** [comment]
@nvuillam does the `.sqlfluff` file need to be in the root directory of the repo rather than in `.github/linters`?

@odette-ppb fonyou want to give that a go?

**Comment by gregmaghakian** [comment]
FWIW, mine is in the root directory of the repo, and working fine with mega linter.

**Comment by nvuillam** [comment]
Hmmmm I get it, sqlfluff is skipepd if there is no `.sqlfluff` in the root repository
I can make a update the file names described are also checked within .github/linters

https://github.com/megalinter/megalinter/blob/5cc076531be20c11580083b52d1a970f7e53700d/megalinter/descriptors/sql.megalinter-descriptor.yml#L34

**Comment by nvuillam** [comment]
Check of existence is also performed within .github/linters except if you overridden LINTER_RULES_PATH :)

https://github.com/megalinter/megalinter/blob/31554fe725a87910528fc6f195d2e3dd5692d17c/megalinter/Linter.py#L261
