### ISSUE TITLE
Extremely slow kotlin linting

### ISSUE THREAD

**Issue by powturns** [megalinter/megalinter#1441]
We've been using megalinter across several projects. Things have been going well, except on an android project where the linting run takes almost 15 minutes to complete. 

```
> docker run -v $(pwd):/workspace -e DEFAULT_WORKSPACE='/workspace' -e ENABLE_LINTERS='KOTLIN_KTLINT' megalinter/megalinter-java:v5

+----MATCHING LINTERS-+----------+----------------+------------+
| Descriptor | Linter | Criteria | Matching files | Format/Fix |
+------------+--------+----------+----------------+------------+
| KOTLIN     | ktlint | .kt|.kts | 464            | no         |
+------------+--------+----------+----------------+------------+
+----SUMMARY-+--------+------+-------+-------+--------+--------------+
| Descriptor | Linter | Mode | Files | Fixed | Errors | Elapsed time |
+------------+--------+------+-------+-------+--------+--------------+
| ✅ KOTLIN  | ktlint | file |   464 |       |      0 |      849.19s |
+------------+--------+------+-------+-------+--------+--------------+

```

vs. running ktlint directly:
```
> time ktlint 
ktlint  12.78s user 0.69s system 185% cpu 7.262 total
```

Any advice as to where to start troubleshooting is much appreciated.

**Comment by nvuillam** [comment]
The problem comes from the `file` method used ... ktlint is called once by file, that's what explain such unacceptable elapsed time

I am not sure than ktlint can take a list of files as parameter (or maybe you can check ? ), that's why `list_of_files` mode is not used.

Meanwhile, if you don't want to ignore some of the ktlint files, please can you try to define `KOTLIN_KTLINT_CLI_LINT_MODE: project` in env var or `.mega-linter.yml` ? It will may ktlint be called just once on the directory, and you should see the same performances that with your local test :)

**Comment by powturns** [comment]
That's done it, thanks very much!
